# Quality Assessment of Food Knowledge Graph

The goal is to craft rules to identify at least 10 different data quality issues across multiple dimensions including **semantic accuracy**, **consistency**, **completeness**, **conciseness**.

In [28]:
# If pyshacl is not installed, you can install it using pip:
# !pip install pyshacl

In [29]:
# Import required libraries
import rdflib
from rdflib import Graph, Literal, Namespace, BNode
from rdflib.collection import Collection
from pyshacl import validate, shapes_graph
import re
from collections import defaultdict
import pandas as pd

## Exploration of the knowledge graph

Before we can create SHACL shapes to validate the knowledge graph, we need to explore the structure and content of the `food_kg.ttl` file. This exploration will help us understand the classes, properties, and data types used in the knowledge graph, which will inform the design of our SHACL shapes.

In [30]:
food_kg = Graph().parse("data/food_kg.ttl", format="ttl")
print(f"Food KG contains {len(food_kg)} triples.")

ontology_kg = Graph().parse("data/food_kg_ontology.ttl")

Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x00000217E029BC40>
Traceback (most recent call last):
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x00000217E029BC40>
Traceback (most recent call last):
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x00000217E029BC40>
Traceback (most recent call last):
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x00000217E029BC40>
Traceback (most recent call last):
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x00000217E029BC40>
Traceback (most recent call last):
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ada\AppData\Local\Programs\Python\Python312\Lib\site-packages\rdflib\xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan

Food KG contains 1801 triples.

We already see that there are problems with the graph as there is an error from the rdflib parser. This is a strong indication of potential quality issues in the graph. We will need to investigate these issues further during our exploration and validation process.

In [31]:
# Find the classes defined in the ONTOLOGY graph
result = ontology_kg.query("""
    PREFIX schema: <https://schema.org/>
    SELECT DISTINCT ?subject
    {
        ?s a ?type.
    }
 """)
df = pd.DataFrame(result.bindings)
df

Empty DataFrame
Columns: []
Index: [0]

In [32]:
# Find the classes used in the DATA graph and their frequency
result = food_kg.query("""
    PREFIX schema: <https://schema.org/>
    SELECT ?type (COUNT(?type) as ?count) ?type WHERE {
        ?s a ?type.
    }
    GROUP BY ?type
    ORDER BY DESC(?count)
 """)
df = pd.DataFrame(result.bindings)
df

  count                                            type
0    55                       https://schema.org/Recipe
1    14  http://www.w3.org/2002/07/owl#DatatypeProperty
2     3             http://www.w3.org/2002/07/owl#Class
3     2    http://www.w3.org/2002/07/owl#ObjectProperty
4     1                      https://schema.org/Product
5     1           http://dbpedia.org/ontology/Nutrition

A very important observaiton here is that there is no metnion of the `schema:NutritionInformation` class in the data graph, which is a key class that we would expect to be present in a food and nutrition knowledge graph. This is a strong indication of a **completeness** issue in the knowledge graph.

Moreover, here we can see a `dbo:Nutrition` class, which is an alternative for `schema:NutritionInformation` from dbpedia and a `schema:Product` class, which was not mentioned in the ontology graph at all, let's check what subjects use these types:

In [33]:
res = food_kg.query(f"""
PREFIX schema: <https://schema.org/>
PREFIX dbo: <http://dbpedia.org/ontology/>


SELECT DISTINCT ?subject ?type
WHERE {{
  ?subject rdf:type ?type .
                   
FILTER(?type = schema:Product || ?type = dbo:Nutrition)
}}""")

display(pd.DataFrame(res, columns=[str(var) for var in res.vars]))

,subject,type
0,http://kg-course/food-nutrition/recipe/38,https://schema.org/Product
1,http://kg-course/food-nutrition/recipe/46/nutr...,http://dbpedia.org/ontology/Nutrition

One recipe instance has actually type of `schema:Product`, instead of `schema:Recipe`, while nutrition information object uses `dbo:Nutrition`, instead of `schema:NutritionInformation`. Presence of `dbo:Nutrition` may indicate issues with **conciseness** and **consistency** and usage of  `schema:Product` class further proofs problems with **consistency**.

---

In [34]:
# Find the properties used in the knowledge graph and their frequency
result = food_kg.query("""
    SELECT ?property (COUNT(?property) as ?count) WHERE {
        ?s ?property ?o.
    }
    GROUP BY ?property
    ORDER BY DESC(?count)
 """)
df = pd.DataFrame(result.bindings)
df

   count                                         property
0    502            https://schema.org/recipeInstructions
1    343              https://schema.org/recipeIngredient
2    246                      https://schema.org/keywords
3     76  http://www.w3.org/1999/02/22-rdf-syntax-ns#type
4     58                https://schema.org/recipeCategory
5     56                      https://schema.org/prepTime
6     56                          https://schema.org/name
7     56                      https://schema.org/cookTime
8     56                 https://schema.org/datePublished
9     44                         https://schema.org/image
10    34                   https://schema.org/recipeYield
11    20                  https://schema.org/fiberContent
12    20                    https://schema.org/fatContent
13    20                  https://schema.org/sugarContent
14    20           https://schema.org/carbohydrateContent
15    20                 https://schema.org/sodiumContent
16    20                      https://schema.org/calories
17    20                https://schema.org/proteinContent
18    19       http://www.w3.org/2000/01/rdf-schema#label
19    19           https://schema.org/saturatedFatContent
20    19            https://schema.org/cholesterolContent
21    18                   https://schema.org/description
22    16      http://www.w3.org/2000/01/rdf-schema#domain
23    16       http://www.w3.org/2000/01/rdf-schema#range
24    13     http://www.w3.org/2000/01/rdf-schema#comment
25    13                     https://schema.org/nutrition
26     1  http://www.w3.org/2000/01/rdf-schema#subClassOf

We can see from this query that there are many properties used in the knowledge graph, with varying frequencies. This indicates that there is a **completeness** issue. If there are 55 recipes in the grpah, then there should be at least 55 instances of the `schema:nutrition` property, as well as other recipe related properties such as `schema:recipeYield` e.t.c. In the defined `food_kg_ontology.ttl` file it is specified that the `schema:nutrition` property should link to an instance of the `schema:NutritionInformation` class, but as we have seen from the previous query, there are no instances of this class in the graph, which further confirms the **completeness** issue in the knowledge graph. In addition, the presnece of properties that are not defined in the ontology, such as `schema:recipeYield`, also indicates a **consistency** issue in the knowledge graph, as the data does not conform to the defined ontology.

We also do not see any `owl:sameAs` properties in the graph, which is an indication of an **interpoerability** issue, as we would expect to see some links to external entities or identifiers in a knowledge graph. In addition to this there is no provenance information in the graph, such as `schema:source` or `schema:reference`, which is another indication of an **interoperability** issue, as provenance information is important for understanding the origin and reliability of the data in the knowledge graph.

## Create the SHACL shapes

SHACL shapes define constraints on the structure and content of RDF data. These shapes will be used to validate the quality of the knowledge graph in `food_kg.ttl`. The goal is to identify different data quality issues that fall under semantic accuracy, consistency, completeness and conciseness.

In [35]:

# Define namespaces
OWL = Namespace('http://www.w3.org/2002/07/owl#')
RDF = Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
RDFS = Namespace('http://www.w3.org/2000/01/rdf-schema#')
XSD = Namespace('http://www.w3.org/2001/XMLSchema#')
SCHEMA = Namespace('https://schema.org/')
DBO = Namespace('http://dbpedia.org/ontology/')
DBR = Namespace('http://dbpedia.org/resource/')
SH = Namespace('http://www.w3.org/ns/shacl#')
KGS = Namespace('http://kg-course.io/food-nutrition/')

# Parse the ontology graph
ontology_g = Graph().parse('data/food_kg_ontology.ttl', format='ttl')

# Create a new graph for SHACL shapes
shapes_g = Graph()
shapes_g.bind('owl', OWL)
shapes_g.bind('rdf', RDF)
shapes_g.bind('rdfs', RDFS)
shapes_g.bind('xsd', XSD)
shapes_g.bind('schema', SCHEMA)
shapes_g.bind('dbo', DBO)
shapes_g.bind('dbr', DBR)
shapes_g.bind('sh', SH)
shapes_g.bind('kgs', KGS)

def get_name_from_uri(uri) -> str:
    return uri.split('#')[-1] if '#' in uri else uri.split('/')[-1]

# Procedure to create SHACL shapes for classes from an ontology graph
def create_class_shape(ontology_graph: Graph, shapes_graph: Graph):
    for cls in ontology_graph.subjects(RDF.type, OWL.Class):
        if cls == DBO.Nutrition:
            continue
            # print(f"Creating shape for {cls}")
        shape_name = get_name_from_uri(cls) + "Shape"
        shapes_graph.add((KGS[shape_name], RDF.type, SH.NodeShape))
        shapes_graph.add((KGS[shape_name], SH.targetClass, cls))
        shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.IRI))

# Procedure to create SHACL properties from an ontology graph
def create_property_shape(ontology_graph: Graph, shapes_graph: Graph):
    for prop in ontology_graph.subjects(RDF.type, [OWL.ObjectProperty, OWL.DatatypeProperty]):
        # Get the domain and range of the property
        domain = ontology_graph.value(prop, RDFS.domain)
        range = ontology_graph.value(prop, RDFS.range)
        # Get the names of the domain and range to creaet the shape name
        node_name = get_name_from_uri(domain) + "Shape"
        shape_name = node_name + f"_{get_name_from_uri(prop)}"
        # Add the property shape to the graph
        shapes_graph.add((KGS[node_name], SH.property, KGS[shape_name]))
        shapes_graph.add((KGS[shape_name], RDF.type, SH.PropertyShape))
        shapes_graph.add((KGS[shape_name], SH.path, prop))

        # If range is a datatype string, we explicitly state that it MUST be a language string
        if get_name_from_uri(range) == 'string':
            shapes_graph.add((KGS[shape_name], SH.datatype, RDF.langString))
            list_node = BNode()
            Collection(shapes_graph, list_node, [Literal('en')])
            shapes_graph.add((KGS[shape_name], SH.languageIn, list_node))
            shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.Literal))
        # If property range is a link to the NutritionInformation class, we use different sh property(sh:class)
        elif get_name_from_uri(range) == "NutritionInformation":
            shapes_graph.add((KGS[shape_name], SH["class"], range))
            shapes_graph.add((KGS[shape_name], SH.maxCount, Literal(1, datatype=XSD.integer)))
            shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.IRI))
        # If datatype is numerical or a duration, then it MUST be positive(properties we have described amount of one or another element or time. As we know neither of those can be negative)
        elif get_name_from_uri(range) == "duration" or get_name_from_uri(range) in ["float", "double", "decimal"]:
            shapes_graph.add((KGS[shape_name], SH.datatype, range))
            shapes_graph.add((KGS[shape_name], SH.minInclusive, Literal("PT0S" if range==XSD.duration else 0.0, datatype=range)))
            shapes_graph.add((KGS[shape_name], SH.maxCount, Literal(1, datatype=XSD.integer)))
            shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.Literal))

        shapes_graph.add((KGS[shape_name], SH.minCount, Literal(1, datatype=XSD.integer)))
    # print(shapes_graph.serialize(format='turtle'))

# Create the class and property shapes based on the ontology graph
create_class_shape(ontology_g, shapes_g)
create_property_shape(ontology_g, shapes_g)

# Serialize the SHACL shapes graph to a file and print it
shapes_g.serialize(destination='../data/food_kg_shapes.ttl', format='ttl')
print(shapes_g.serialize(format='turtle'))

@prefix kgs: <http://kg-course.io/food-nutrition/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

kgs:NutritionInformationShape a sh:NodeShape ;
    sh:nodeKind sh:IRI ;
    sh:property kgs:NutritionInformationShape_calories,
        kgs:NutritionInformationShape_carbohydrateContent,
        kgs:NutritionInformationShape_cholesterolContent,
        kgs:NutritionInformationShape_fatContent,
        kgs:NutritionInformationShape_fiberContent,
        kgs:NutritionInformationShape_proteinContent,
        kgs:NutritionInformationShape_saturatedFatContent,
        kgs:NutritionInformationShape_sodiumContent,
        kgs:NutritionInformationShape_sugarContent ;
    sh:targetClass <http://schema.org/NutritionInformation> .

kgs:RecipeShape a sh:NodeShape ;
    sh:nodeKind sh:IRI ;
    sh:property kgs:RecipeShape_cookTime,
        kgs:RecipeShape_name,
        kgs:RecipeShape_nutrition,
        kgs:RecipeShape_prepTime,
        kgs:RecipeShape_recipeCategory,
        kgs:RecipeShape_recipeIngredient,
        kgs:RecipeShape_recipeInstructions ;
    sh:targetClass <http://schema.org/Recipe> .

kgs:NutritionInformationShape_calories a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/calories> .

kgs:NutritionInformationShape_carbohydrateContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/carbohydrateContent> .

kgs:NutritionInformationShape_cholesterolContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/cholesterolContent> .

kgs:NutritionInformationShape_fatContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/fatContent> .

kgs:NutritionInformationShape_fiberContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/fiberContent> .

kgs:NutritionInformationShape_proteinContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/proteinContent> .

kgs:NutritionInformationShape_saturatedFatContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/saturatedFatContent> .

kgs:NutritionInformationShape_sodiumContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/sodiumContent> .

kgs:NutritionInformationShape_sugarContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/sugarContent> .

kgs:RecipeShape_cookTime a sh:PropertyShape ;
    sh:datatype xsd:duration ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive "P0D"^^xsd:duration ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/cookTime> .

kgs:RecipeShape_name a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/name> .

kgs:RecipeShape_nutrition a sh:PropertyShape ;
    sh:class <http://schema.org/NutritionInformation> ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:nodeKind sh:IRI ;
    sh:path <http://schema.org/nutrition> .

kgs:RecipeShape_prepTime a sh:PropertyShape ;
    sh:datatype xsd:duration ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive "P0D"^^xsd:duration ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/prepTime> .

kgs:RecipeShape_recipeCategory a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/recipeCategory> .

kgs:RecipeShape_recipeIngredient a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/recipeIngredient> .

kgs:RecipeShape_recipeInstructions a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path <http://schema.org/recipeInstructions> .

## Validate the knowledge graph using the created SHACL shapes
Now that we have created the SHACL shapes based on the ontology, we can use these shapes to validate the `food_kg.ttl` knowledge graph. The validation will check for any violations of the constraints defined in the SHACL shapes, such as missing properties, incorrect data types, or structural issues.

In [36]:
shape_kg = Graph().parse("data/food_kg_shapes.ttl")

conforms, v_graph, v_text = validate(data_graph=food_kg, shacl_graph=shape_kg, inference='both', debug=False, serialize_report_graph="ttl")

In [37]:
print(conforms)

True

In [38]:
# print(v_graph)

In [39]:
print(v_text)

Validation Report
Conforms: True

## Use the validation graph to identify data quality issues

In [40]:
# Extract the violations from the validation graph
def extract_violations(validation_graph: Graph):
    violations = []
    for violation in validation_graph.subjects(RDF.type, SH.ValidationResult):
        focus_node = validation_graph.value(violation, SH.focusNode)
        result_path = validation_graph.value(violation, SH.resultPath)
        value = validation_graph.value(violation, SH.value)
        source_shape = validation_graph.value(violation, SH.sourceShape)
        source_constraint = validation_graph.value(violation, SH.sourceConstraintComponent)
        message = validation_graph.value(violation, SH.resultMessage)
        severity = validation_graph.value(violation, SH.resultSeverity)
        violations.append({
            "focus_node": focus_node,
            "result_path": result_path,
            "value": value,
            "message": str(message) if message is not None else None,
            "severity": get_name_from_uri(severity) if severity is not None else None,
            "sourceShape": get_name_from_uri(source_shape) if source_shape is not None else None,
            "sourceConstraint": get_name_from_uri(source_constraint) if source_constraint is not None else None,
            "raw": violation
        })
    return violations

# Function that categorises the violation
def categorise_violation(violation):
    # Get the relevant information from the violation and convert to lowercase for easier matching
    sc = (violation.get("sourceConstraint") or "").lower()
    msg = (violation.get("message") or "").lower()
    path = (str(violation.get("result_path") or "")).lower()

    # Sort the violation into a category based on the source constraint component
    if sc:
        if "datatype" in sc:
            return "datatype_mismatch"
        if "mincount" in sc or "maxcount" in sc:
            return "cardinality"
        if "languagein" in sc or "language" in sc:
            return "language_tag"
        if "mininclusive" in sc or "maxinclusive" in sc or "range" in sc:
            return "range_violation"
        if "classconstraint" in sc or "class" in sc:
            return "class_violation"
        if "nodekind" in sc:
            return "nodekind_violation"
        if "sparqlconstraint" in sc:
            return "sparql_constraint"

    # fallback heuristics on message / path
    if re.search(r'\bnan\b|\bnan\b', msg):
        return "invalid_lexical_nan"
    if re.search(r'duration|xsd:duration', msg) or "duration" in path:
        return "duration_parse_error"
    if "datatype" in msg or "literal" in msg:
        return "datatype_mismatch"
    if "mincount" in msg or "maxcount" in msg or "cardinality" in msg or "more than one" in msg:
        return "cardinality"
    if "language" in msg or "languagein" in msg:
        return "language_tag"
    if "mininclusive" in msg or "maxinclusive" in msg or "out of range" in msg:
        return "range_violation"
    if "not a" in msg and "class" in msg:
        return "class_violation"
    if "duplicate" in msg or "multiple" in msg:
        return "duplicate_values"
    # default
    return "other"

# function analyse the validaiton graph from pyshacl
def analyse_validation_graph(validation_graph: Graph, examples_per_issue=3):
    violations = extract_violations(validation_graph)
    categorised_violations = defaultdict(list)
    for v in violations:
        cat = categorise_violation(v)
        categorised_violations[cat].append(v)

    # Print summary
    total = len(violations)
    print(f"Total validation results: {total}")
    for cat, items in sorted(categorised_violations.items(), key=lambda x: -len(x[1])):
        print(f"\nCategory: {cat} — {len(items)} issue(s)")
        for ex in items[:examples_per_issue]:
            print("  - focus node:", ex['focus_node'],
                  " result path:", ex['result_path'],
                  " value:", ex['value'],
                  " src:", ex['sourceConstraint'],
                  " msg:", (ex['message'] or "")[:120])
    # Save report if desired
    try:
        validation_graph.serialize(destination='data/food_kg_report.ttl', format='ttl')
        print("\nSaved SHACL report to `data/food_kg_report.ttl`")
    except Exception:
        pass

    return categorised_violations

violations_graph = Graph().parse(v_graph, format="ttl", encoding="utf-8")
categories = analyse_validation_graph(violations_graph)
print(len(categories), "distinct QC categories found")

Total validation results: 0
0 distinct QC categories found

# Analyse semantic inconsistencies
Looking at the first 100 recipes, we compare the ingredients and the instruction for inconsistencies. We take 2 approaches the SPARQL one, were we retrieve the raw ingredient string and the raw instruction then post process using the standard library "re" to compare the strings. The second approach is an NLP approach where we analyse the words using NLP techniques. This method uses a HuggingFace zero-shot classifier (facebook/bart-large-mnli) to detect whether the instruction text semantically involves each declared ingredient.  This catches synonym mismatches that string matching misses (e.g. "spring onions" listed but instructions say "scallions"). The model can also be changed, but for simplicity reasons we chose an open source NLP trained model.

# SPARQL-based analysis

In [ ]:
# SPARQL-based approach
# Steps:
#     - split the ingredient string on commas → ingredient tokens
#     - normalise both strings (lowercase, strip punctuation)
#     - check which ingredient tokens cannot be found anywhere in the
#       instruction text → those are "ghost ingredients" (declared but
#       never mentioned in the steps)

import re
from rdflib import Graph, Namespace

SCHEMA = Namespace("https://schema.org/")

sparql_query = """
PREFIX schema: <https://schema.org/>
SELECT ?recipe ?ingredients ?instructions
WHERE {
    ?recipe a schema:Recipe ;
            schema:recipeIngredient ?ingredients ;
            schema:recipeInstructions ?instructions .
}
"""

results = list(food_kg.query(sparql_query))
print(f"Fetched {len(results)} recipes for SPARQL analysis.")


def normalise(text: str) -> str:
    """Lowercase and strip all non-alphanumeric characters."""
    return re.sub(r"[^a-z0-9 ]", " ", text.lower())


def tokenise_ingredients(raw: str) -> list[str]:
    """
    Split a comma-separated ingredient string into individual ingredient
    tokens, normalising each one.  Multi-word ingredients (e.g. 'lemon juice')
    are kept as phrases so we can check for the whole phrase in the steps.
    """
    return [normalise(t).strip() for t in raw.split(",") if t.strip()]


def find_ghost_ingredients(ingredients: list[str], instructions_norm: str) -> list[str]:
    """
    Return ingredients that do not appear (even partially) in the
    instruction text.  A partial word-boundary match is used so that
    'tomato' matches 'tomatoes'.
    """
    ghosts = []
    for ing in ingredients:
        if ing and ing not in instructions_norm:
            # Fallback: check if every individual word of the ingredient
            # appears somewhere in the instructions (catches "lemon juice"
            # when instructions say "squeeze some lemon and add the juice").
            words = ing.split()
            if not all(w in instructions_norm for w in words if len(w) > 2):
                ghosts.append(ing)
    return ghosts


sparql_inconsistencies = []

for row in results:
    recipe_uri        = str(row.recipe)
    raw_ing           = str(row.ingredients)
    raw_inst          = str(row.instructions)
    ingredients       = tokenise_ingredients(raw_ing)
    instructions_norm = normalise(raw_inst)
    ghosts            = find_ghost_ingredients(ingredients, instructions_norm)

    if ghosts:
        sparql_inconsistencies.append({
            "recipe":            recipe_uri,
            "ghost_ingredients": ghosts,
            "n_declared":        len(ingredients),
            "n_missing":         len(ghosts),
        })

total_recipes   = len(results)
flagged_recipes = len(sparql_inconsistencies)
print(f"SPARQL-based inconsistency report (all {total_recipes} recipes)")
print(f"  Recipes analysed : {total_recipes}")
print(f"  Recipes flagged  : {flagged_recipes} ({100*flagged_recipes/total_recipes:.1f}%)")
print(f"\nTop 15 inconsistencies (most missing ingredients all):")
print(f"{'Recipe URI':<55} {'Declared':>9} {'Missing':>8}  Ghost ingredients")
print("-" * 110)

top15 = sorted(sparql_inconsistencies, key=lambda x: -x["n_missing"])[:15]
for item in top15:
    short_uri  = item["recipe"].split("/")[-1]
    ghosts_str = ", ".join(item["ghost_ingredients"][:5])
    if len(item["ghost_ingredients"]) > 5:
        ghosts_str += f" … (+{len(item['ghost_ingredients'])-5} more)"
    print(f"  recipe/{short_uri:<49} {item['n_declared']:>9} {item['n_missing']:>8}  {ghosts_str}")

df_sparql = pd.DataFrame(sparql_inconsistencies)
df_sparql["pct_missing"] = (df_sparql["n_missing"] / df_sparql["n_declared"] * 100).round(1)
display(df_sparql[["recipe", "n_declared", "n_missing", "pct_missing"]].sort_values("pct_missing", ascending=False).head(20))

Fetched 3716 recipes for SPARQL analysis.
SPARQL-based inconsistency report (all 3716 recipes)
  Recipes analysed : 3716
  Recipes flagged  : 3368 (90.6%)

Top 15 inconsistencies (most missing ingredients all):
Recipe URI                                               Declared  Missing  Ghost ingredients
--------------------------------------------------------------------------------------------------------------
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans

,recipe,n_declared,n_missing,pct_missing
0,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
1,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
2,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
3,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
4,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
5,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
6,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
7,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
8,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
9,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
10,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
11,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
12,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
13,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
14,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
15,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
16,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
17,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
18,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
19,http://kg-course/food-nutrition/recipe/121241,1,1,100.0

In [47]:
top50 = sorted(sparql_inconsistencies, key=lambda x: -x["n_missing"])[:50]
for item in top50:
    short_uri  = item["recipe"].split("/")[-1]
    ghosts_str = ", ".join(item["ghost_ingredients"][:5])
    if len(item["ghost_ingredients"]) > 5:
        ghosts_str += f" … (+{len(item['ghost_ingredients'])-5} more)"
    print(f"  recipe/{short_uri:<49} {item['n_declared']:>9} {item['n_missing']:>8}  {ghosts_str}")

df_sparql = pd.DataFrame(sparql_inconsistencies)
df_sparql["pct_missing"] = (df_sparql["n_missing"] / df_sparql["n_declared"] * 100).round(1)
display(df_sparql[["recipe", "n_declared", "n_missing", "pct_missing"]].sort_values("pct_missing", ascending=False).head(50))

  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/323316                                                    2        2  1 lemon, zest of
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 egg
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 pecans
  recipe/100573                                                    1        1  1 vanilla instant pudding mix
  recipe/100573                                                    1        1  1 vanilla instant pudding mix
  recipe/100573                                                    1        1  1 vanilla instant pudding mix
  recipe/100573                                                    1        1  1 vanilla instant pudding mix
  recipe/100573                                                    1        1  1 vanilla instant pudding mix
  recipe/100573                                                    1        1  1 vanilla instant pudding mix
  recipe/121241                                                    1        1  1 eggs
  recipe/121241                                                    1        1  1 eggs
  recipe/121241                                                    1        1  1 eggs
  recipe/121241                                                    1        1  1 eggs
  recipe/121241                                                    1        1  1 eggs
  recipe/121241                                                    1        1  1 margarine
  recipe/121241                                                    1        1  1 margarine
  recipe/121241                                                    1        1  1 margarine
  recipe/121241                                                    1        1  1 margarine
  recipe/121241                                                    1        1  1 margarine
  recipe/121241                                                    1        1  1 2 butter
  recipe/121241                                                    1        1  1 2 butter
  recipe/121241                                                    1        1  1 2 butter
  recipe/121241                                                    1        1  1 2 butter
  recipe/121241                                                    1        1  1 2 butter
  recipe/121241                                                    1        1  1 2 butter
  recipe/121241                                                    1        1  2 vanilla extract
  recipe/121241                                                    1        1  2 vanilla extract
  recipe/121241                                                    1        1  2 vanilla extract
  recipe/121241                                                    1        1  2 vanilla extract
  recipe/121241                                                    1        1  2 vanilla extract
  recipe/121241                                                    1        1  2 vanilla extract
  recipe/121241                                                    1        1  6  8 pecans
  recipe/121241                                                    1        1  6  8 pecans
  recipe/121241                                                    1        1  6  8 pecans
  recipe/121241                                                    1        1  6  8 pecans
  recipe/121241                                                    1        1  6  8 pecans
  recipe/142426                                                    1        1  1 flour

,recipe,n_declared,n_missing,pct_missing
0,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
1,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
2,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
3,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
4,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
5,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
6,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
7,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
8,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
9,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
10,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
11,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
12,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
13,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
14,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
15,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
16,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
17,http://kg-course/food-nutrition/recipe/100573,1,1,100.0
18,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
19,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
20,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
21,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
22,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
23,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
24,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
25,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
26,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
27,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
28,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
29,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
30,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
31,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
32,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
33,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
34,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
35,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
36,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
37,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
38,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
39,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
40,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
41,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
42,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
43,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
44,http://kg-course/food-nutrition/recipe/121241,1,1,100.0
45,http://kg-course/food-nutrition/recipe/142426,1,1,100.0
46,http://kg-course/food-nutrition/recipe/142426,1,1,100.0
47,http://kg-course/food-nutrition/recipe/142426,1,1,100.0
48,http://kg-course/food-nutrition/recipe/142426,1,1,100.0
49,http://kg-course/food-nutrition/recipe/142426,1,1,100.0

# NLP Approach: NLP-based ingredient–instruction inconsistency detection
If not already installed run `pip install tf-keras` before running the next cell. If you don't you might get this error:
- If ValueError: Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

In [45]:
# NLP-based approach

import os
os.environ["USE_TF"] = "0"   # disable TF backend before importing transformers
# Check they mentioned all ingredients
from transformers import pipeline

THRESHOLD      = 0.50   # consistent-score below this → flagged
INST_MAX_CHARS = 400    # truncate instructions to keep inference fast

print("Loading zero-shot classification model (facebook/bart-large-mnli) …")
print("This may take a moment on first run while the model is downloaded.")
classifier = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=-1,   # CPU; set to 0 for GPU
)
print("Model loaded.\n")


def truncate(text: str, max_chars: int = INST_MAX_CHARS) -> str:
    """Truncate text to at most max_chars characters at a word boundary."""
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rsplit(" ", 1)[0] + " …"


# Build (recipe, ingredient, instruction_snippet) triples from the SPARQL results
candidates = []
for row in results:
    recipe_uri   = str(row.recipe)
    raw_ing      = str(row.ingredients)
    inst_snippet = truncate(str(row.instructions))
    for ing in raw_ing.split(","):
        ing = ing.strip()
        if ing:
            candidates.append((recipe_uri, ing, inst_snippet))

print(f"Total (recipe, ingredient) pairs to classify: {len(candidates)}")

# Run zero-shot classification for each pair
nlp_inconsistencies = []

for i, (recipe_uri, ingredient, inst_text) in enumerate(candidates):
    output = classifier(
        inst_text,
        candidate_labels=["consistent", "inconsistent"],
        hypothesis_template="{}.",
    )
    scores           = dict(zip(output["labels"], output["scores"]))
    consistent_score = scores["consistent"]
    if consistent_score < THRESHOLD:
        nlp_inconsistencies.append({
            "recipe":             recipe_uri,
            "ingredient":         ingredient,
            "consistent_score":   round(consistent_score, 3),
            "inconsistent_score": round(1 - consistent_score, 3),
        })
    if (i + 1) % 50 == 0:
        print(f"  … classified {i+1}/{len(candidates)} pairs")

print(f"\nClassification complete.  Flagged {len(nlp_inconsistencies)} inconsistent pairs.")

# Summary
df_nlp = pd.DataFrame(nlp_inconsistencies)

if df_nlp.empty:
    print("No NLP-detected inconsistencies at the chosen threshold.")
else:
    recipe_counts = (
        df_nlp.groupby("recipe")
              .agg(n_flagged=("ingredient", "count"),
                   avg_inconsistent_score=("inconsistent_score", "mean"))
              .reset_index()
              .sort_values("n_flagged", ascending=False)
    )
    print(f"NLP-based inconsistency report (threshold = {THRESHOLD})")
    print(f"  Recipes with ≥1 flagged ingredient : {len(recipe_counts)}")
    print(f"  Total flagged pairs                : {len(df_nlp)}\n")

    for _, r in recipe_counts.head(15).iterrows():
        short = r["recipe"].split("/")[-1]
        print(f"  recipe/{short:<49} flagged={int(r['n_flagged'])}  avg_score={r['avg_inconsistent_score']:.3f}")

    display(
        df_nlp.sort_values("inconsistent_score", ascending=False)
              .head(20)[["recipe", "ingredient", "consistent_score", "inconsistent_score"]]
              .reset_index(drop=True)
    )

Loading zero-shot classification model (facebook/bart-large-mnli) …
This may take a moment on first run while the model is downloaded.

Device set to use cpu

Model loaded.

Total (recipe, ingredient) pairs to classify: 3721
  … classified 50/3721 pairs
  … classified 100/3721 pairs
  … classified 150/3721 pairs
  … classified 200/3721 pairs
  … classified 250/3721 pairs
  … classified 300/3721 pairs
  … classified 350/3721 pairs
  … classified 400/3721 pairs
  … classified 450/3721 pairs
  … classified 500/3721 pairs
  … classified 550/3721 pairs
  … classified 600/3721 pairs
  … classified 650/3721 pairs
  … classified 700/3721 pairs
  … classified 750/3721 pairs
  … classified 800/3721 pairs
  … classified 850/3721 pairs
  … classified 900/3721 pairs
  … classified 950/3721 pairs
  … classified 1000/3721 pairs
  … classified 1050/3721 pairs
  … classified 1100/3721 pairs
  … classified 1150/3721 pairs
  … classified 1200/3721 pairs
  … classified 1250/3721 pairs
  … classified 1300/3721 pairs
  … classified 1350/3721 pairs
  … classified 1400/3721 pairs
  … classified 1450/3721 pairs
  … classified 1500/3721 pairs
  … classified 1550/3721 pairs
  … classified 1600/3721 pairs
  … classified 1650/3721 pairs
  … classified 1700/3721 pairs
  … classified 1750/3721 pairs
  … classified 1800/3721 pairs
  … classified 1850/3721 pairs
  … classified 1900/3721 pairs
  … classified 1950/3721 pairs
  … classified 2000/3721 pairs
  … classified 2050/3721 pairs
  … classified 2100/3721 pairs
  … classified 2150/3721 pairs
  … classified 2200/3721 pairs
  … classified 2250/3721 pairs
  … classified 2300/3721 pairs
  … classified 2350/3721 pairs
  … classified 2400/3721 pairs
  … classified 2450/3721 pairs
  … classified 2500/3721 pairs
  … classified 2550/3721 pairs
  … classified 2600/3721 pairs
  … classified 2650/3721 pairs
  … classified 2700/3721 pairs
  … classified 2750/3721 pairs
  … classified 2800/3721 pairs
  … classified 2850/3721 pairs
  … classified 2900/3721 pairs
  … classified 2950/3721 pairs
  … classified 3000/3721 pairs
  … classified 3050/3721 pairs
  … classified 3100/3721 pairs
  … classified 3150/3721 pairs
  … classified 3200/3721 pairs
  … classified 3250/3721 pairs
  … classified 3300/3721 pairs
  … classified 3350/3721 pairs
  … classified 3400/3721 pairs
  … classified 3450/3721 pairs
  … classified 3500/3721 pairs
  … classified 3550/3721 pairs
  … classified 3600/3721 pairs
  … classified 3650/3721 pairs
  … classified 3700/3721 pairs

Classification complete.  Flagged 185 inconsistent pairs.
NLP-based inconsistency report (threshold = 0.5)
  Recipes with ≥1 flagged ingredient : 9
  Total flagged pairs                : 185

  recipe/57856                                             flagged=57  avg_score=0.728
  recipe/237567                                            flagged=45  avg_score=0.866
  recipe/58643                                             flagged=18  avg_score=0.842
  recipe/74837                                             flagged=18  avg_score=0.597
  recipe/48                                                flagged=15  avg_score=0.945
  recipe/244649                                            flagged=13  avg_score=0.807
  recipe/88096                                             flagged=9  avg_score=0.987
  recipe/245931                                            flagged=6  avg_score=0.679
  recipe/314970                                            flagged=4  avg_score=0.778

,recipe,ingredient,consistent_score,inconsistent_score
0,http://kg-course/food-nutrition/recipe/88096,2 onions,0.013,0.987
1,http://kg-course/food-nutrition/recipe/88096,1 coarse salt,0.013,0.987
2,http://kg-course/food-nutrition/recipe/88096,2 brown sugar,0.013,0.987
3,http://kg-course/food-nutrition/recipe/88096,2 beef flank steak,0.013,0.987
4,http://kg-course/food-nutrition/recipe/88096,2 Italian plum tomatoes,0.013,0.987
5,http://kg-course/food-nutrition/recipe/88096,1/2 fresh ground pepper,0.013,0.987
6,http://kg-course/food-nutrition/recipe/88096,1/2 - 3/4 tomato paste,0.013,0.987
7,http://kg-course/food-nutrition/recipe/88096,1 kosher salt,0.013,0.987
8,http://kg-course/food-nutrition/recipe/88096,1 cabbage,0.013,0.987
9,http://kg-course/food-nutrition/recipe/48,1 milk,0.055,0.945
10,http://kg-course/food-nutrition/recipe/48,3 baking powder,0.055,0.945
11,http://kg-course/food-nutrition/recipe/48,1/2 margarine,0.055,0.945
12,http://kg-course/food-nutrition/recipe/48,1 1/2 eggs,0.055,0.945
13,http://kg-course/food-nutrition/recipe/48,1 1/2 sugar,0.055,0.945
14,http://kg-course/food-nutrition/recipe/48,1 butter,0.055,0.945
15,http://kg-course/food-nutrition/recipe/48,1 1/2 flour,0.055,0.945
16,http://kg-course/food-nutrition/recipe/48,2 1/4 cake flour,0.055,0.945
17,http://kg-course/food-nutrition/recipe/48,2 milk,0.055,0.945
18,http://kg-course/food-nutrition/recipe/48,1 sugar,0.055,0.945
19,http://kg-course/food-nutrition/recipe/48,1 salt,0.055,0.945

In [46]:
# Cross-method comparison
sparql_flagged_uris = {item["recipe"] for item in sparql_inconsistencies}
nlp_flagged_uris    = set(df_nlp["recipe"].unique()) if not df_nlp.empty else set()

only_sparql = sparql_flagged_uris - nlp_flagged_uris
only_nlp    = nlp_flagged_uris - sparql_flagged_uris
both        = sparql_flagged_uris & nlp_flagged_uris

print("Cross-method comparison")
print(f"  Flagged by SPARQL only : {len(only_sparql)}  (exact string mismatch only)")
print(f"  Flagged by NLP only    : {len(only_nlp)}  (semantic mismatch, synonym-aware)")
print(f"  Flagged by BOTH        : {len(both)}  (strong evidence of inconsistency)")
print("\nRecipes flagged by BOTH methods:")
for uri in sorted(both)[:10]:
    print(f"  {uri}")

Cross-method comparison
  Flagged by SPARQL only : 25  (exact string mismatch only)
  Flagged by NLP only    : 0  (semantic mismatch, synonym-aware)
  Flagged by BOTH        : 9  (strong evidence of inconsistency)

Recipes flagged by BOTH methods:
  http://kg-course/food-nutrition/recipe/237567
  http://kg-course/food-nutrition/recipe/244649
  http://kg-course/food-nutrition/recipe/245931
  http://kg-course/food-nutrition/recipe/314970
  http://kg-course/food-nutrition/recipe/48
  http://kg-course/food-nutrition/recipe/57856
  http://kg-course/food-nutrition/recipe/58643
  http://kg-course/food-nutrition/recipe/74837
  http://kg-course/food-nutrition/recipe/88096