# Quality Assessment of Food Knowledge Graph

The goal is to craft rules to identify at least 10 different data quality issues across multiple dimensions including **semantic accuracy**, **consistency**, **completeness**, **conciseness**.

In [1]:
# Import required libraries
import rdflib
from rdflib import Graph, Literal, Namespace, BNode
from rdflib.collection import Collection
from pyshacl import validate, shapes_graph
import re
from collections import defaultdict
import pandas as pd

## Exploration of the knowledge graph

Before we can create SHACL shapes to validate the knowledge graph, we need to explore the structure and content of the `food_kg.ttl` file. This exploration will help us understand the classes, properties, and data types used in the knowledge graph, which will inform the design of our SHACL shapes.

In [2]:
food_kg = Graph().parse("data/food_kg.ttl", format="ttl")
print(f"Food KG contains {len(food_kg)} triples.")

Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan

Food KG contains 1801 triples.

We already see that there are problems with the graph as there is an error from the rdflib parser. This is a strong indication of potential quality issues in the graph. We will need to investigate these issues further during our exploration and validation process.

In [3]:
# Find the classes used in the knowledge graph and their frequency
result = food_kg.query("""
    PREFIX schema: <https://schema.org/>
    SELECT ?type (COUNT(?type) as ?count) ?type WHERE {
        ?s a ?type.
    }
    GROUP BY ?type
    ORDER BY DESC(?count)
 """)
df = pd.DataFrame(result.bindings)
df

                                             type count
0                       https://schema.org/Recipe    55
1  http://www.w3.org/2002/07/owl#DatatypeProperty    14
2             http://www.w3.org/2002/07/owl#Class     3
3    http://www.w3.org/2002/07/owl#ObjectProperty     2
4                      https://schema.org/Product     1
5           http://dbpedia.org/ontology/Nutrition     1

A very important observaiton here is that there is no metnion of the `schema:NutritionInformation` class in the graph, which is a key class that we would expect to be present in a food and nutrition knowledge graph. This is a strong indication of a **completeness** issue in the knowledge graph.

In [4]:
# Find the properties used in the knowledge graph and their frequency
result = food_kg.query("""
    SELECT ?property (COUNT(?property) as ?count) WHERE {
        ?s ?property ?o.
    }
    GROUP BY ?property
    ORDER BY DESC(?count)
 """)
df = pd.DataFrame(result.bindings)
df

                                           property count
0             https://schema.org/recipeInstructions   502
1               https://schema.org/recipeIngredient   343
2                       https://schema.org/keywords   246
3   http://www.w3.org/1999/02/22-rdf-syntax-ns#type    76
4                 https://schema.org/recipeCategory    58
5                           https://schema.org/name    56
6                  https://schema.org/datePublished    56
7                       https://schema.org/cookTime    56
8                       https://schema.org/prepTime    56
9                          https://schema.org/image    44
10                   https://schema.org/recipeYield    34
11                      https://schema.org/calories    20
12                  https://schema.org/sugarContent    20
13           https://schema.org/carbohydrateContent    20
14                    https://schema.org/fatContent    20
15                  https://schema.org/fiberContent    20
16                 https://schema.org/sodiumContent    20
17                https://schema.org/proteinContent    20
18            https://schema.org/cholesterolContent    19
19       http://www.w3.org/2000/01/rdf-schema#label    19
20           https://schema.org/saturatedFatContent    19
21                   https://schema.org/description    18
22       http://www.w3.org/2000/01/rdf-schema#range    16
23      http://www.w3.org/2000/01/rdf-schema#domain    16
24     http://www.w3.org/2000/01/rdf-schema#comment    13
25                     https://schema.org/nutrition    13
26  http://www.w3.org/2000/01/rdf-schema#subClassOf     1

We can see from this query that there are many properties used in the knowledge graph, with varying frequencies. This indicates that there is a **completeness** issue. If there are 55 recipes in the grpah, then there should be at least 55 instances of the `schema:nutrition` property, as well as other recipe related properties such as `schema:recipeYield` e.t.c. In the defined `food_kg_ontology.ttl` file it is specified that the `schema:nutrition` property should link to an instance of the `schema:NutritionInformation` class, but as we have seen from the previous query, there are no instances of this class in the graph, which further confirms the **completeness** issue in the knowledge graph. In addition, the presnece of properties that are not defined in the ontology, such as `schema:recipeYield`, also indicates a **consistency** issue in the knowledge graph, as the data does not conform to the defined ontology.

We also do not see any `owl:sameAs` properties in the graph, which is an indication of an **interpoerability** issue, as we would expect to see some links to external entities or identifiers in a knowledge graph. In addition to this there is no provenance information in the graph, such as `schema:source` or `schema:reference`, which is another indication of an **interoperability** issue, as provenance information is important for understanding the origin and reliability of the data in the knowledge graph.

## Create the SHACL shapes

SHACL shapes define constraints on the structure and content of RDF data. These shapes will be used to validate the quality of the knowledge graph in `food_kg.ttl`. The goal is to identify different data quality issues that fall under semantic accuracy, consistency, completeness and conciseness.

In [5]:

# Define namespaces
OWL = Namespace('http://www.w3.org/2002/07/owl#')
RDF = Namespace('http://www.w3.org/1999/02/22-rdf-syntax-ns#')
RDFS = Namespace('http://www.w3.org/2000/01/rdf-schema#')
XSD = Namespace('http://www.w3.org/2001/XMLSchema#')
SCHEMA = Namespace('https://schema.org/')
DBO = Namespace('http://dbpedia.org/ontology/')
DBR = Namespace('http://dbpedia.org/resource/')
SH = Namespace('http://www.w3.org/ns/shacl#')
KGS = Namespace('http://kg-course.io/food-nutrition/')

# Parse the ontology graph
ontology_g = Graph().parse('data/food_kg_ontology.ttl', format='ttl')

# Create a new graph for SHACL shapes
shapes_g = Graph()
shapes_g.bind('owl', OWL)
shapes_g.bind('rdf', RDF)
shapes_g.bind('rdfs', RDFS)
shapes_g.bind('xsd', XSD)
shapes_g.bind('schema', SCHEMA)
shapes_g.bind('dbo', DBO)
shapes_g.bind('dbr', DBR)
shapes_g.bind('sh', SH)
shapes_g.bind('kgs', KGS)

def get_name_from_uri(uri) -> str:
    return uri.split('#')[-1] if '#' in uri else uri.split('/')[-1]

# Procedure to create SHACL shapes for classes from an ontology graph
def create_class_shape(ontology_graph: Graph, shapes_graph: Graph):
    for cls in ontology_graph.subjects(RDF.type, OWL.Class):
        if cls == DBO.Nutrition:
            continue
            # print(f"Creating shape for {cls}")
        shape_name = get_name_from_uri(cls) + "Shape"
        shapes_graph.add((KGS[shape_name], RDF.type, SH.NodeShape))
        shapes_graph.add((KGS[shape_name], SH.targetClass, cls))
        shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.IRI))

# Procedure to create SHACL properties from an ontology graph
def create_property_shape(ontology_graph: Graph, shapes_graph: Graph):
    for prop in ontology_graph.subjects(RDF.type, [OWL.ObjectProperty, OWL.DatatypeProperty]):
        # Get the domain and range of the property
        domain = ontology_graph.value(prop, RDFS.domain)
        range = ontology_graph.value(prop, RDFS.range)
        # Get the names of the domain and range to creaet the shape name
        node_name = get_name_from_uri(domain) + "Shape"
        shape_name = node_name + f"_{get_name_from_uri(prop)}"
        # Add the property shape to the graph
        shapes_graph.add((KGS[node_name], SH.property, KGS[shape_name]))
        shapes_graph.add((KGS[shape_name], RDF.type, SH.PropertyShape))
        shapes_graph.add((KGS[shape_name], SH.path, prop))

        # If range is a datatype string, we explicitly state that it MUST be a language string
        if get_name_from_uri(range) == 'string':
            shapes_graph.add((KGS[shape_name], SH.datatype, RDF.langString))
            list_node = BNode()
            Collection(shapes_graph, list_node, [Literal('en')])
            shapes_graph.add((KGS[shape_name], SH.languageIn, list_node))
            shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.Literal))
        # If property range is a link to the NutritionInformation class, we use different sh property(sh:class)
        elif get_name_from_uri(range) == "NutritionInformation":
            shapes_graph.add((KGS[shape_name], SH["class"], range))
            shapes_graph.add((KGS[shape_name], SH.maxCount, Literal(1, datatype=XSD.integer)))
            shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.IRI))
        # If datatype is numerical or a duration, then it MUST be positive(properties we have described amount of one or another element or time. As we know neither of those can be negative)
        elif get_name_from_uri(range) == "duration" or get_name_from_uri(range) in ["float", "double", "decimal"]:
            shapes_graph.add((KGS[shape_name], SH.datatype, range))
            shapes_graph.add((KGS[shape_name], SH.minInclusive, Literal("PT0S" if range==XSD.duration else 0.0, datatype=range)))
            shapes_graph.add((KGS[shape_name], SH.maxCount, Literal(1, datatype=XSD.integer)))
            shapes_graph.add((KGS[shape_name], SH.nodeKind, SH.Literal))

        shapes_graph.add((KGS[shape_name], SH.minCount, Literal(1, datatype=XSD.integer)))
    # print(shapes_graph.serialize(format='turtle'))

# Create the class and property shapes based on the ontology graph
create_class_shape(ontology_g, shapes_g)
create_property_shape(ontology_g, shapes_g)

# Serialize the SHACL shapes graph to a file and print it
shapes_g.serialize(destination='data/food_kg_shapes.ttl', format='ttl')
print(shapes_g.serialize(format='turtle'))

@prefix kgs: <http://kg-course.io/food-nutrition/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema: <https://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

kgs:NutritionInformationShape a sh:NodeShape ;
    sh:nodeKind sh:IRI ;
    sh:property kgs:NutritionInformationShape_calories,
        kgs:NutritionInformationShape_carbohydrateContent,
        kgs:NutritionInformationShape_cholesterolContent,
        kgs:NutritionInformationShape_fatContent,
        kgs:NutritionInformationShape_fiberContent,
        kgs:NutritionInformationShape_proteinContent,
        kgs:NutritionInformationShape_saturatedFatContent,
        kgs:NutritionInformationShape_sodiumContent,
        kgs:NutritionInformationShape_sugarContent ;
    sh:targetClass schema:NutritionInformation .

kgs:RecipeShape a sh:NodeShape ;
    sh:nodeKind sh:IRI ;
    sh:property kgs:RecipeShape_cookTime,
        kgs:RecipeShape_name,
        kgs:RecipeShape_nutrition,
        kgs:RecipeShape_prepTime,
        kgs:RecipeShape_recipeCategory,
        kgs:RecipeShape_recipeIngredient,
        kgs:RecipeShape_recipeInstructions ;
    sh:targetClass schema:Recipe .

kgs:NutritionInformationShape_calories a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:calories .

kgs:NutritionInformationShape_carbohydrateContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:carbohydrateContent .

kgs:NutritionInformationShape_cholesterolContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:cholesterolContent .

kgs:NutritionInformationShape_fatContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:fatContent .

kgs:NutritionInformationShape_fiberContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:fiberContent .

kgs:NutritionInformationShape_proteinContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:proteinContent .

kgs:NutritionInformationShape_saturatedFatContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:saturatedFatContent .

kgs:NutritionInformationShape_sodiumContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:sodiumContent .

kgs:NutritionInformationShape_sugarContent a sh:PropertyShape ;
    sh:datatype xsd:double ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive 0e+00 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:sugarContent .

kgs:RecipeShape_cookTime a sh:PropertyShape ;
    sh:datatype xsd:duration ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive "P0D"^^xsd:duration ;
    sh:nodeKind sh:Literal ;
    sh:path schema:cookTime .

kgs:RecipeShape_name a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:name .

kgs:RecipeShape_nutrition a sh:PropertyShape ;
    sh:class schema:NutritionInformation ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:nodeKind sh:IRI ;
    sh:path schema:nutrition .

kgs:RecipeShape_prepTime a sh:PropertyShape ;
    sh:datatype xsd:duration ;
    sh:maxCount 1 ;
    sh:minCount 1 ;
    sh:minInclusive "P0D"^^xsd:duration ;
    sh:nodeKind sh:Literal ;
    sh:path schema:prepTime .

kgs:RecipeShape_recipeCategory a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:recipeCategory .

kgs:RecipeShape_recipeIngredient a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:recipeIngredient .

kgs:RecipeShape_recipeInstructions a sh:PropertyShape ;
    sh:datatype rdf:langString ;
    sh:languageIn ( "en" ) ;
    sh:minCount 1 ;
    sh:nodeKind sh:Literal ;
    sh:path schema:recipeInstructions .

## Validate the knowledge graph using the created SHACL shapes
Now that we have created the SHACL shapes based on the ontology, we can use these shapes to validate the `food_kg.ttl` knowledge graph. The validation will check for any violations of the constraints defined in the SHACL shapes, such as missing properties, incorrect data types, or structural issues.

In [6]:
data_g = Graph()
data_g.parse("data/food_kg.ttl")

shape_g = Graph()
shape_g.parse("data/food_kg_shapes.ttl")

conforms, v_graph, v_text = validate(data_graph=data_g, shacl_graph=shape_g, inference='both', debug=False, serialize_report_graph="ttl")

Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan

In [7]:
print(conforms)

False

In [8]:
# print(v_graph)

In [9]:
# print(v_text)

## Use the validation graph to identify data quality issues

In [10]:
# Extract the violations from the validation graph
def extract_violations(validation_graph: Graph):
    violations = []
    for violation in validation_graph.subjects(RDF.type, SH.ValidationResult):
        focus_node = validation_graph.value(violation, SH.focusNode)
        result_path = validation_graph.value(violation, SH.resultPath)
        value = validation_graph.value(violation, SH.value)
        source_shape = validation_graph.value(violation, SH.sourceShape)
        source_constraint = validation_graph.value(violation, SH.sourceConstraintComponent)
        message = validation_graph.value(violation, SH.resultMessage)
        severity = validation_graph.value(violation, SH.resultSeverity)
        violations.append({
            "focus_node": focus_node,
            "result_path": result_path,
            "value": value,
            "message": str(message) if message is not None else None,
            "severity": get_name_from_uri(severity) if severity is not None else None,
            "sourceShape": get_name_from_uri(source_shape) if source_shape is not None else None,
            "sourceConstraint": get_name_from_uri(source_constraint) if source_constraint is not None else None,
            "raw": violation
        })
    return violations

# Function that categorises the violation
def categorise_violation(violation):
    # Get the relevant information from the violation and convert to lowercase for easier matching
    sc = (violation.get("sourceConstraint") or "").lower()
    msg = (violation.get("message") or "").lower()
    path = (str(violation.get("result_path") or "")).lower()

    # Sort the violation into a category based on the source constraint component
    if sc:
        if "datatype" in sc:
            return "datatype_mismatch"
        if "mincount" in sc or "maxcount" in sc:
            return "cardinality"
        if "languagein" in sc or "language" in sc:
            return "language_tag"
        if "mininclusive" in sc or "maxinclusive" in sc or "range" in sc:
            return "range_violation"
        if "classconstraint" in sc or "class" in sc:
            return "class_violation"
        if "nodekind" in sc:
            return "nodekind_violation"
        if "sparqlconstraint" in sc:
            return "sparql_constraint"

    # fallback heuristics on message / path
    if re.search(r'\bnan\b|\bnan\b', msg):
        return "invalid_lexical_nan"
    if re.search(r'duration|xsd:duration', msg) or "duration" in path:
        return "duration_parse_error"
    if "datatype" in msg or "literal" in msg:
        return "datatype_mismatch"
    if "mincount" in msg or "maxcount" in msg or "cardinality" in msg or "more than one" in msg:
        return "cardinality"
    if "language" in msg or "languagein" in msg:
        return "language_tag"
    if "mininclusive" in msg or "maxinclusive" in msg or "out of range" in msg:
        return "range_violation"
    if "not a" in msg and "class" in msg:
        return "class_violation"
    if "duplicate" in msg or "multiple" in msg:
        return "duplicate_values"
    # default
    return "other"

# function analyse the validaiton graph from pyshacl
def analyse_validation_graph(validation_graph: Graph, examples_per_issue=3):
    violations = extract_violations(validation_graph)
    categorised_violations = defaultdict(list)
    for v in violations:
        cat = categorise_violation(v)
        categorised_violations[cat].append(v)

    # Print summary
    total = len(violations)
    print(f"Total validation results: {total}")
    for cat, items in sorted(categorised_violations.items(), key=lambda x: -len(x[1])):
        print(f"\nCategory: {cat} — {len(items)} issue(s)")
        for ex in items[:examples_per_issue]:
            print("  - focus node:", ex['focus_node'],
                  " result path:", ex['result_path'],
                  " value:", ex['value'],
                  " src:", ex['sourceConstraint'],
                  " msg:", (ex['message'] or "")[:120])
    # Save report if desired
    try:
        validation_graph.serialize(destination='data/food_kg_report.ttl', format='ttl')
        print("\nSaved SHACL report to `data/food_kg_report.ttl`")
    except Exception:
        pass

    return categorised_violations

violations_graph = Graph().parse(v_graph, format="ttl", encoding="utf-8")
categories = analyse_validation_graph(violations_graph)
print(len(categories), "distinct QC categories found")

Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan
Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#duration, Converter=<function parse_xsd_duration at 0x10c07f060>
Traceback (most recent call last):
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/term.py", line 2262, in _castLexicalToPython
    return conv_func(lexical)  # type: ignore[arg-type]
  File "/Users/alexanderleonidas/Maastricht University/AI Masters/KEN4256 Building and Mining Knowledge Graphs/fluffy_octo_spoon/venv/lib/python3.13/site-packages/rdflib/xsd_datetime.py", line 427, in parse_xsd_duration
    raise ValueError("Unable to parse duration string " + dur_string)
ValueError: Unable to parse duration string nan

Total validation results: 121

Category: cardinality — 100 issue(s)
  - focus node: cholesterol  result path: https://schema.org/fiberContent  value: None  src: MinCountConstraintComponent  msg: Less than 1 values on Literal("cholesterol")->schema:fiberContent
  - focus node: http://kg-course/food-nutrition/recipe/321461  result path: https://schema.org/nutrition  value: None  src: MinCountConstraintComponent  msg: Less than 1 values on <http://kg-course/food-nutrition/recipe/321461>->schema:nutrition
  - focus node: http://kg-course/food-nutrition/recipe/213018  result path: https://schema.org/nutrition  value: None  src: MinCountConstraintComponent  msg: Less than 1 values on <http://kg-course/food-nutrition/recipe/213018>->schema:nutrition

Category: datatype_mismatch — 9 issue(s)
  - focus node: http://kg-course/food-nutrition/recipe/41/nutrition  result path: https://schema.org/fiberContent  value: -0.2  src: DatatypeConstraintComponent  msg: Value is not Literal with datatype xsd:double
  - focus node: http://kg-course/food-nutrition/recipe/280584  result path: https://schema.org/cookTime  value: nan  src: DatatypeConstraintComponent  msg: Value is not Literal with datatype xsd:duration
  - focus node: http://kg-course/food-nutrition/recipe/42/nutrition  result path: https://schema.org/fiberContent  value: 0.2  src: DatatypeConstraintComponent  msg: Value is not Literal with datatype xsd:double

Category: range_violation — 9 issue(s)
  - focus node: http://kg-course/food-nutrition/recipe/162371  result path: https://schema.org/cookTime  value: nan  src: MinInclusiveConstraintComponent  msg: Value is not >= Literal("P0D" = 0:00:00, datatype=xsd:duration)
  - focus node: http://kg-course/food-nutrition/recipe/45/nutrition  result path: https://schema.org/proteinContent  value: -4.2  src: MinInclusiveConstraintComponent  msg: Value is not >= Literal("0.0", datatype=xsd:double)
  - focus node: http://kg-course/food-nutrition/recipe/41/nutrition  result path: https://schema.org/fiberContent  value: -0.2  src: MinInclusiveConstraintComponent  msg: Value is not >= Literal("0.0", datatype=xsd:double)

Category: nodekind_violation — 2 issue(s)
  - focus node: http://kg-course/food-nutrition/recipe/48  result path: https://schema.org/nutrition  value: cholesterol  src: NodeKindConstraintComponent  msg: Value is not of Node Kind sh:IRI
  - focus node: cholesterol  result path: None  value: cholesterol  src: NodeKindConstraintComponent  msg: Value is not of Node Kind sh:IRI

Category: class_violation — 1 issue(s)
  - focus node: http://kg-course/food-nutrition/recipe/48  result path: https://schema.org/nutrition  value: cholesterol  src: ClassConstraintComponent  msg: Value does not have class schema:NutritionInformation

Saved SHACL report to `data/food_kg_report.ttl`
5 distinct QC categories found